# Generated by Django 3.0.4 on 2020-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('achievement_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PinPurchaseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('purchase_dt', models.DateTimeField()),
            ],
        ),
    ]
