# Generated by Django 3.0.4 on 2020-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED')], max_length=16)),
                ('place_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('action_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OPENED', 'OPENED'), ('CREATED', 'CREATED'), ('EDITED', 'EDITED'), ('DELETED', 'DELETED')], max_length=16)),
                ('place_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField(null=True)),
                ('action_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('old_rating', models.PositiveIntegerField()),
                ('new_rating', models.PositiveIntegerField()),
                ('action_dt', models.DateTimeField()),
            ],
        ),
    ]
