# Generated by Django 3.0.4 on 2020-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=16)),
                ('user_id', models.PositiveIntegerField(default=None, null=True)),
                ('endpoint', models.CharField(max_length=256)),
                ('gateway_process_time', models.FloatField()),
                ('status_code', models.PositiveIntegerField()),
                ('is_fully_processed', models.BooleanField(default=True)),
                ('cb_start_state', models.CharField(choices=[('OPEN', 'OPEN'), ('HALF-OPEN', 'HALF-OPEN'), ('CLOSED', 'CLOSED')], default='CLOSE', max_length=16)),
                ('cb_end_state', models.CharField(choices=[('OPEN', 'OPEN'), ('HALF-OPEN', 'HALF-OPEN'), ('CLOSED', 'CLOSED')], default='CLOSE', max_length=16)),
                ('queue_length', models.PositiveIntegerField()),
                ('request_dt', models.DateTimeField()),
            ],
        ),
    ]
