# Generated by Django 3.0.4 on 2020-04-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestStats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestsstats',
            old_name='gateway_process_time',
            new_name='process_time',
        ),
        migrations.RemoveField(
            model_name='requestsstats',
            name='cb_end_state',
        ),
        migrations.RemoveField(
            model_name='requestsstats',
            name='cb_start_state',
        ),
        migrations.RemoveField(
            model_name='requestsstats',
            name='is_fully_processed',
        ),
        migrations.RemoveField(
            model_name='requestsstats',
            name='queue_length',
        ),
    ]
