name: Heroku CD

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.0.4
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: "gordiig@gmail.com"
          heroku_app_name: "gordiig-rsoi-stats"
